### 日志总配置 ###
log4j.rootLogger = info,stdout

### 输出到控制台日志 ###
log4j.appender.stdout = org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target = System.out
log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern = [%d] %p %C.%M(%L) | %m%n 

########################################################################################
### 配置Netty的日志 ###
log4j.logger.io.netty = DEBUG, nettyLog

### 使用滚动文件日志 ###
log4j.appender.nettyLog = org.apache.log4j.DailyRollingFileAppender
### 日志文件 ###
log4j.appender.nettyLog.File = logs/netty.log
### 滚动日志文件命名方式 ###
log4j.appender.nettyLog.DatePattern = '.'yyyy-MM-dd-HH'.log'
### 文件编码方式 ###
log4j.appender.nettyLog.encoding = UTF-8
# 日志等级 #
log4j.appender.nettyLog.Threshold = DEBUG
### 布局样式 ###
log4j.appender.nettyLog.layout = org.apache.log4j.PatternLayout  
### 布局模版 ###
log4j.appender.nettyLog.layout.ConversionPattern = [%d] %p %C.%M(%L) | %m%n 
### 开启缓冲区 ###
log4j.appender.nettyLog.BufferedIO = true
### 缓冲区大小: 8KB ###
log4j.appender.nettyLog.BufferSize = 8096

########################################################################################
### 配置Netty的日志 ###
log4j.logger.com.wills = DEBUG, klzzLog
log4j.logger.com.klzz = DEBUG, klzzLog


### 使用滚动文件日志 ###
log4j.appender.klzzLog = org.apache.log4j.DailyRollingFileAppender
### 日志文件 ###
log4j.appender.klzzLog.File = logs/socket.log
### 滚动日志文件命名方式 ###
log4j.appender.klzzLog.DatePattern='.'yyyy-MM-dd-HH'.log'
### 文件编码方式 ###
log4j.appender.klzzLog.encoding = UTF-8
# 日志等级 #
log4j.appender.klzzLog.Threshold = DEBUG
### 布局样式 ###
log4j.appender.klzzLog.layout = org.apache.log4j.PatternLayout  
### 布局模版 ###
log4j.appender.klzzLog.layout.ConversionPattern = [%d] %p %C.%M(%L) | %m%n 
### 开启缓冲区 ###
log4j.appender.klzzLog.BufferedIO = true
### 缓冲区大小: 8KB ###
log4j.appender.klzzLog.BufferSize = 8096
