# Copy this file to socket.properties and fill in values for your environment.

domain = <domain>
publicIP = 0.0.0.0
ip = 0.0.0.0
idle = 800
port = 9001
maxConnections = 12000
maxUserConnections = 10000
maxQueue = 20
adminPort = 6666
key = <verification-key>
openMonitor = false
keepUserStatus = true
keepStatusTime = 900000
maxTimeOut = 20000
cachePath = ./cache
cacheMode = false

offline = false
offlineUrl = <offline-url>

online = true
onlineUrl = <online-url>

sslKey = <ssl-key>
isSSL = false
sslFile = <certificate-file>.jks
