import { assetExport, assetSrc } from '../elements/builtinAssets';
import type { Element } from '../types';
import type { PresetTemplate } from './types';

const videoElements: Element[] = [
  {
    id: 'el-video-bg',
    type: 'Video',
    layaType: 'Box',
    name: 'VideoBg',
    x: 0, y: 0,
    width: 1920, height: 1080,
    opacity: 1, rotation: 0,
    locked: true,
    actions: [],
    props: { videoUrl: '' },
  },
];

// 作业模板库：从 D:\demo\s8_demo_01_hw 的关卡 1 提取，资源改走内置 builtin 管线。
const s8Demo01HomeworkElements: Element[] = [
  {
    id: 'el-s8-demo-01-hw-bg',
    type: 'NewImage',
    layaType: 'Image',
    name: 'NewImage_1',
    x: 2,
    y: 1,
    width: 1920,
    height: 1080,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      skin: assetExport('preset.homework.s8Demo01.bg'),
      _naturalWidth: 1920,
      _naturalHeight: 1080,
    },
  },
  {
    id: 'el-s8-demo-01-hw-question-label',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_1',
    x: 133,
    y: 75,
    width: 88,
    height: 62,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: 'Q1:',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s8-demo-01-hw-title',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_2',
    x: 216,
    y: 76,
    width: 1136,
    height: 65,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s8-demo-01-hw-body',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_3',
    x: 150,
    y: 276,
    width: 1458,
    height: 295,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
];

// 作业模板库：从 D:\demo\s4_demo_01_hw 的关卡 2 提取，资源改走内置 builtin 管线。
const s4Demo01HomeworkStage2Elements: Element[] = [
  {
    id: 'el-s4-demo-01-hw-stage-2-bg',
    type: 'NewImage',
    layaType: 'Image',
    name: 'NewImage_2',
    x: 2,
    y: -1,
    width: 1920,
    height: 1080,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      skin: assetExport('preset.homework.s4Demo01.stage2.bg'),
      _naturalWidth: 1920,
      _naturalHeight: 1080,
    },
  },
  {
    id: 'el-s4-demo-01-hw-stage-2-title-bg',
    type: 'NewImage',
    layaType: 'Image',
    name: 'NewImage_3',
    x: 193,
    y: 28,
    width: 1259,
    height: 180,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      skin: assetExport('preset.homework.s4Demo01.stage2.title'),
      _naturalWidth: 1841,
      _naturalHeight: 520,
    },
  },
  {
    id: 'el-s4-demo-01-hw-stage-2-question-label',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_1',
    x: 262,
    y: 66,
    width: 96,
    height: 108,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: 'Q3：',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s4-demo-01-hw-stage-2-title',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_2',
    x: 365,
    y: 66,
    width: 1026,
    height: 137,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑2',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s4-demo-01-hw-stage-2-body',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_3',
    x: 231,
    y: 346,
    width: 1458,
    height: 137,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
];

// 专题测评模板库：从 D:\demo\s8_sse_test_01 的关卡 1 提取，资源改走内置 builtin 管线。
const s8SseTest01EvaluationStage1Elements: Element[] = [
  {
    id: 'el-s8-sse-test-01-stage-1-bg',
    type: 'NewImage',
    layaType: 'Image',
    name: 'NewImage_1',
    x: -2,
    y: 0,
    width: 1920,
    height: 1080,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      skin: assetExport('preset.sEvaluation.s8SseTest01.stage1.bg'),
      _naturalWidth: 1920,
      _naturalHeight: 1080,
    },
  },
  {
    id: 'el-s8-sse-test-01-stage-1-question-label',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_1',
    x: 125,
    y: 72,
    width: 96,
    height: 60,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: 'Q1：',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s8-sse-test-01-stage-1-title',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_2',
    x: 206,
    y: 72,
    width: 1163,
    height: 67,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
  {
    id: 'el-s8-sse-test-01-stage-1-body',
    type: 'NewTextArea',
    layaType: 'TextArea',
    name: 'NewTextArea_3',
    x: 125,
    y: 268,
    width: 1458,
    height: 285,
    opacity: 1,
    rotation: 0,
    actions: [],
    props: {
      text: '文本编辑',
      fontSize: 38,
      color: '#0d0d0d',
      leading: 24,
      wordWrap: true,
      align: 'left',
      valign: 'top',
      mouseEnabled: false,
      fontLibraryId: 'paipeiyou.lantinghei',
      fontLocalPath: '',
    },
  },
];

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'internal-pages-v1',
    labelKey: 'presetInternalPages',
    thumbnail: '',
    elements: [],
    editorModel: 'internal-pages',
    defaultStageName: '内部页面关卡',
    defaultSubPageName: '内部页面关卡',
  },
  {
    id: 'video',
    labelKey: 'presetVideo',
    thumbnail: assetSrc('preset.video'),
    elements: videoElements,
    noSubPages: true,
    frozen: true,
    alwaysVisible: true,
    defaultStageName: '视频关卡',
    defaultSubPageName: '视频关卡',
  },
  {
    id: 's8-demo-01-hw-stage-1',
    labelKey: 'presetS8Demo01Homework',
    thumbnail: assetSrc('preset.homework.s8Demo01.bg'),
    elements: s8Demo01HomeworkElements,
    category: 'homework',
    defaultStageName: 'S8作业关卡1',
    defaultSubPageName: '小关卡 1-1',
  },
  {
    id: 's4-demo-01-hw-stage-2',
    labelKey: 'presetHomeworkLevel2',
    thumbnail: assetSrc('preset.homework.s4Demo01.stage2.bg'),
    elements: s4Demo01HomeworkStage2Elements,
    category: 'homework',
    defaultStageName: '作业关卡2',
    defaultSubPageName: '小关卡 2-1',
  },
  {
    id: 's8-sse-test-01-stage-1',
    labelKey: 'presetSEvaluationLevel1',
    thumbnail: assetSrc('preset.sEvaluation.s8SseTest01.stage1.bg'),
    elements: s8SseTest01EvaluationStage1Elements,
    category: 'sEvaluation',
    defaultStageName: '专题测评关卡1',
    defaultSubPageName: '小关卡 1-1',
  },
];
